project_id = "zrcpadiqlfkshhbznwao"

[functions.dispatch-notification]
verify_jwt = false

[functions.process-purchase]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.daily-reminders]
verify_jwt = false

[functions.trial-payment-reminder]
verify_jwt = false

[functions.subscription-payment]
verify_jwt = false
